<a href="https://colab.research.google.com/github/subhobrata/Tensorflow_github/blob/master/Concept02_embedding_lookup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
sess = tf.InteractiveSession()

In [0]:
embeddings_0d = tf.constant([17,22,35,51])

In [0]:
embeddings_4d = tf.constant([[1, 0, 0, 0],
                             [0, 1, 0, 0],
                             [0, 0, 1, 0],
                             [0, 0, 0, 1]])

In [0]:
embeddings_2x2d = tf.constant([[[1, 0], [0, 0]],
                               [[0, 1], [0, 0]],
                               [[0, 0], [1, 0]],
                               [[0, 0], [0, 1]]])

In [0]:

ids = tf.constant([1, 0, 2])

In [6]:
lookup_0d = sess.run(tf.nn.embedding_lookup(embeddings_0d, ids))
print(lookup_0d)

Instructions for updating:
Colocations handled automatically by placer.
[22 17 35]


In [7]:
lookup_4d = sess.run(tf.nn.embedding_lookup(embeddings_4d, ids))
print(lookup_4d)

[[0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]]


In [8]:
lookup_2x2d = sess.run(tf.nn.embedding_lookup(embeddings_2x2d, ids))
print(lookup_2x2d)

[[[0 1]
  [0 0]]

 [[1 0]
  [0 0]]

 [[0 0]
  [1 0]]]
